import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joe's Life",
  description: "Generated by Joe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <div className="cursor-pointer relative rounded-bl-md rounded-br-md md:rounded-lg w-full overflow-hidden md:my-1 h-full">
        <div className="absolute -inset-3  bg-gradient-conic from-cyan-100 via-neutral-200 to-cyan-100 dark:bg-black blur opacity-90"></div>
        <div className="relative rounded-bl-lg rounded-br-lg md:rounded-lg flex justify-around">

          <div className="w-full mx-auto justify-evenly min-h-screen bg-neutral-100 dark:bg-black100 max-w-[1400px] drop-shadow-md">
            <Navbar/>
            {children}
          </div>

        </div>
        </div>

      </body>
    </html>
  );
}
