import type { Metadata } from "next";
import { Inter, Unbounded, Archivo } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'
import GlobalAnimationProvider from '@/components/animations/GlobalAnimationProvider'

const inter = Inter({ subsets: ["latin"] });
const unbounded = Unbounded({ weight: ["600", "700", "900"], subsets: ["latin"], variable: "--font-display", display: "swap" });
const archivo = Archivo({ weight: ["400", "500", "600", "700"], subsets: ["latin"], variable: "--font-ui", display: "swap" });

export const metadata: Metadata = {
  title: "Joe's Life",
  description: "Generated by Joe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${unbounded.variable} ${archivo.variable}`}>
      <body className={inter.className}>
        <GlobalAnimationProvider>
          <div id="app-frame" className="w-full h-full bg-gradient-to-r from-cyan-950 via-neutral-400 to-cyan-950">

            <div id="app-panel" className="w-full mx-auto justify-evenly min-h-screen bg-neutral-100 dark:bg-black max-w-[1400px] shadow-2xl shadow-cyan-950 border-l-2 border-r-2 border-cyan-950">
              <Navbar/>
              {children}
            </div>

          </div>
        </GlobalAnimationProvider>
      </body>
    </html>
  );
}
